### ISSUE TITLE
evaluate_algo does not work out of the box

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/reach#246]
Trying to assess changes made in #243 by running `python evaluate_algo.py` as described in [README.md](https://github.com/wellcometrust/policytool/blob/master/README.md#evaluating-each-component-of-the-algorithm) with the following results:

```
$ git pull
Already up-to-date.
$ python evaluate_algo.py
python: can't open file 'evaluate_algo.py': [Errno 2] No such file or directory
$ find ./ -name evaluate_algo.py
./policytool/refparse/evaluate_algo.py
$ python ./policytool/refparse/evaluate_algo.py
Traceback (most recent call last):
  File "./policytool/refparse/evaluate_algo.py", line 96, in <module>
    ), 'w'
FileNotFoundError: [Errno 2] No such file or directory: './algo_evaluation/results/Evaluation results - 2019-10-02-1453.txt'
$ cd policytool/refparse
$ python evaluate_algo.py
./build/virtualenv/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.19.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
./build/virtualenv/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator MultinomialNB from version 0.19.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
./build/virtualenv/lib/python3.6/site-packages/sklearn/base.py:306: UserWarning: Trying to unpickle estimator Pipeline from version 0.19.2 when using version 0.21.3. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
Traceback (most recent call last):
  File "evaluate_algo.py", line 206, in <module>
    settings.LEVENSHTEIN_DIST_SCRAPER_THRESHOLD
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/algo_evaluation/evaluate_find_section.py", line 274, in evaluate_find_section
    section_names, pdf_name, scrape_pdf_location, actual_texts
  File "/home/matthew/Documents/wellcome/policytool/policytool/refparse/algo_evaluation/evaluate_find_section.py", line 250, in scrape_process_pdf
    pdf_file, full_text = parse_pdf_document(f)
```

**Comment by kristinenielsen** [comment]
@ivyleavedtoadflax we are closing this now, if you have any objections, feel free to re-open
