### ISSUE TITLE
Unable to run web image

### ISSUE THREAD

**Issue by SamDepardieu** [wellcometrust/reach#266]
See below:
```
$ kubectl logs -n reach web-6ff6f6d7fd-gwzft
[2019-11-05 14:07:33 +0000] [1] [INFO] Starting gunicorn 19.9.0
[2019-11-05 14:07:33 +0000] [1] [INFO] Listening at: http://0.0.0.0:8080 (1)
[2019-11-05 14:07:33 +0000] [1] [INFO] Using worker: sync
[2019-11-05 14:07:33 +0000] [10] [INFO] Booting worker with pid: 10
/usr/local/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
[2019-11-05 14:07:35 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python3.6/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
  File "/src/policytool/web/wsgi.py", line 2, in <module>
    from . import api
  File "/src/policytool/web/api.py", line 22, in <module>
    raise Exception("No static directory found. STATIC_ROOT=%r" % STATIC_ROOT)
Exception: No static directory found. STATIC_ROOT='/src/reach/web/build/static'
[2019-11-05 14:07:35 +0000] [10] [INFO] Worker exiting (pid: 10)
[2019-11-05 14:07:35 +0000] [1] [INFO] Shutting down: Master
[2019-11-05 14:07:35 +0000] [1] [INFO] Reason: Worker failed to boot.
```
Spotted on https://github.com/wellcometrust/datalabs-infra/pull/291#issuecomment-549838752

**Comment by SamDepardieu** [comment]
After investigation, Reach's Dockerfile does the folowing:
```
COPY build/web/ /build/web/
ENV STATIC_ROOT=/build/web/static
```

The content of the docker-compose file is:
```
      STATIC_ROOT: /build/web/static
```

The kubernetes file is the only one actually looking into:
```
env:
        - name: STATIC_ROOT
          value: "/src/reach/web/build/static"
```

**Comment by jdu** [comment]
As I'm getting the reach application up and running (took EOD yesterday for `make docker-build` to finish running) i'll have a better look at the file paths in `Dockerfile` and `Dockerfile.base` as there seems to be copying going to `/src/reach` and `/reach` in the container which may be what led to the confusion here for paths. Once I have the containers up and running it will be a little easier to see what the actual dir structure we're creating in the container looks like.
