### ISSUE TITLE
Airflow processes not able to write to /opt/airflow

### ISSUE THREAD

**Issue by hblanks** [wellcometrust/reach#281]
Yes, it's mildly offensive, but Airflow wants to be able to write to `/opt/airflow` and can't, so it's failing in localdev:

```
airflow-scheduler_1  | + /opt/airflow/initdb.sh
airflow-scheduler_1  | + exec airflow scheduler
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/usr/local/bin/airflow", line 21, in <module>
airflow-scheduler_1  |     from airflow import configuration
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 31, in <module>
airflow-scheduler_1  |     from airflow.utils.log.logging_mixin import LoggingMixin
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/__init__.py", line 24, in <module>
airflow-scheduler_1  |     from .decorators import apply_defaults as _apply_defaults
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 34, in <module>
airflow-scheduler_1  |     from airflow import settings
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 36, in <module>
airflow-scheduler_1  |     from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/configuration.py", line 565, in <module>
airflow-scheduler_1  |     with open(TEST_CONFIG_FILE, 'w') as f:
airflow-scheduler_1  | PermissionError: [Errno 13] Permission denied: '/opt/airflow/unittests.cfg'
reach_airflow-scheduler_1 exited with code 1
airflow-web_1        | Traceback (most recent call last):
airflow-web_1        |   File "/usr/local/bin/airflow", line 21, in <module>
airflow-web_1        |     from airflow import configuration
airflow-web_1        |   File "/usr/local/lib/python3.6/site-packages/airflow/__init__.py", line 31, in <module>
airflow-web_1        |     from airflow.utils.log.logging_mixin import LoggingMixin
airflow-web_1        |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/__init__.py", line 24, in <module>
airflow-web_1        |     from .decorators import apply_defaults as _apply_defaults
airflow-web_1        |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/decorators.py", line 34, in <module>
airflow-web_1        |     from airflow import settings
airflow-web_1        |   File "/usr/local/lib/python3.6/site-packages/airflow/settings.py", line 36, in <module>
airflow-web_1        |     from airflow.configuration import conf, AIRFLOW_HOME, WEBSERVER_CONFIG  # NOQA F401
airflow-web_1        |   File "/usr/local/lib/python3.6/site-packages/airflow/configuration.py", line 565, in <module>
airflow-web_1        |     with open(TEST_CONFIG_FILE, 'w') as f:
airflow-web_1        | PermissionError: [Errno 13] Permission denied: '/opt/airflow/unittests.cfg'
```

**Comment by hblanks** [comment]
Well, let's just make sure the base image is current first...

**Comment by hblanks** [comment]
Yup, that was all it took.
