### ISSUE TITLE
Encoding issue with PDF metadata through poppler

### ISSUE THREAD

**Issue by jdu** [wellcometrust/reach#363]
Following on from the previous weeks Reach airflow run for the full policy. Both gov_uk and the who_iris flows failed at the ParsePDF stage.

The source of the problem is some additional code I (@jdu) implemented to pull metadata from the PDF files using poppler-utils. It hits an encoding error when dealing with alternately encoded PDF files which trips up the task and stops the completion of the orgs flow in the DAG pipeline.

The log from the airflow task is below.
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 922, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/opt/reach/reach/sentry.py", line 21, in wrapped_f
    return f(*args, **kwargs)
  File "/opt/reach/reach/airflow/tasks/parse_pdf_operator.py", line 57, in execute
    self.dst_s3_key,
  File "/opt/reach/reach/pdf_parser/main.py", line 277, in parse_all_pdf
    write_to_file(output_url, parsed_items, organisation)
  File "/opt/reach/reach/pdf_parser/main.py", line 62, in write_to_file
    for item in items:
  File "/opt/reach/reach/pdf_parser/main.py", line 225, in _yield_items
    metadata_lookup.get(item, {})
  File "/opt/reach/reach/pdf_parser/main.py", line 94, in parse_pdf
    pdf_file, pdf_text, pdf_metadata, errors = parse_pdf_document(pdf)
  File "/opt/reach/reach/pdf_parser/pdf_parse.py", line 86, in parse_pdf_document
    metadata = get_pdf_metadata(document)
  File "/opt/reach/reach/pdf_parser/pdf_parse.py", line 62, in get_pdf_metadata
    string_data = result.stdout.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfe in position 196: invalid start byte
```

**Comment by jdu** [comment]
@TeriForey is working on this.
