### ISSUE TITLE
Error running Reach locally on master

### ISSUE THREAD

**Issue by ivyleavedtoadflax** [wellcometrust/reach#395]
I've just been trying to test https://github.com/wellcometrust/reach/pull/317 having merged master into it, and i'm getting an  error when I try to run `docker-compose up`. So I switched back to master, and I'm getting the same error there:

![image](https://user-images.githubusercontent.com/4583655/73691251-c4503280-46b0-11ea-8eed-69da6bec467f.png)

docker-compose log:

```

[postgres_1           | 2020-02-03 22:07:22.471 UTC [2527] ERROR:  column dag.root_dag_id does not exist at character 34
postgres_1           | 2020-02-03 22:07:22.471 UTC [2527] STATEMENT:  SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval
postgres_1           |  FROM dag
postgres_1           |  WHERE dag.dag_id = 'match_annotated_titles'
postgres_1           |   LIMIT 1
airflow-scheduler_1  | Process DagFileProcessor2338-Process:
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
airflow-scheduler_1  |     cursor, statement, parameters, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
airflow-scheduler_1  |     cursor.execute(statement, parameters)
airflow-scheduler_1  | psycopg2.errors.UndefinedColumn: column dag.root_dag_id does not exist
airflow-scheduler_1  | LINE 1: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root...
airflow-scheduler_1  |                                          ^
airflow-scheduler_1  |
airflow-scheduler_1  |
airflow-scheduler_1  | The above exception was the direct cause of the following exception:
airflow-scheduler_1  |
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
airflow-scheduler_1  |     self.run()
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
airflow-scheduler_1  |     self._target(*self._args, **self._kwargs)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 157, in _run_file_processor
airflow-scheduler_1  |     pickle_dags)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
airflow-scheduler_1  |     return func(*args, **kwargs)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/jobs/scheduler_job.py", line 1559, in process_file
airflow-scheduler_1  |     dag.sync_to_db()
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/utils/db.py", line 74, in wrapper
airflow-scheduler_1  |     return func(*args, **kwargs)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/models/dag.py", line 1371, in sync_to_db
airflow-scheduler_1  |     DagModel).filter(DagModel.dag_id == self.dag_id).first()
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3287, in first
airflow-scheduler_1  |     ret = list(self[0:1])
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3065, in __getitem__
airflow-scheduler_1  |     return list(res)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3389, in __iter__
airflow-scheduler_1  |     return self._execute_and_instances(context)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3414, in _execute_and_instances
airflow-scheduler_1  |     result = conn.execute(querycontext.statement, self._params)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
airflow-scheduler_1  |     return meth(self, multiparams, params)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 293, in _execute_on_connection
airflow-scheduler_1  |     return connection._execute_clauseelement(self, multiparams, params)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
airflow-scheduler_1  |     distilled_params,
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
airflow-scheduler_1  |     e, statement, parameters, cursor, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
airflow-scheduler_1  |     util.raise_from_cause(sqlalchemy_exception, exc_info)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
airflow-scheduler_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
airflow-scheduler_1  |     raise value.with_traceback(tb)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
airflow-scheduler_1  |     cursor, statement, parameters, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
airflow-scheduler_1  |     cursor.execute(statement, parameters)
airflow-scheduler_1  | sqlalchemy.exc.ProgrammingError: (psycopg2.errors.UndefinedColumn) column dag.root_dag_id does not exist
airflow-scheduler_1  | LINE 1: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root...
airflow-scheduler_1  |                                          ^
airflow-scheduler_1  |
airflow-scheduler_1  | [SQL: SELECT dag.dag_id AS dag_dag_id, dag.root_dag_id AS dag_root_dag_id, dag.is_paused AS dag_is_paused, dag.is_subdag AS dag_is_subdag, dag.is_active AS dag_is_active, dag.last_scheduler_run AS dag_last_scheduler_run, dag.last_pickled AS dag_last_pickled, dag.last_expired AS dag_last_expired, dag.scheduler_lock AS dag_scheduler_lock, dag.pickle_id AS dag_pickle_id, dag.fileloc AS dag_fileloc, dag.owners AS dag_owners, dag.description AS dag_description, dag.default_view AS dag_default_view, dag.schedule_interval AS dag_schedule_interval
airflow-scheduler_1  | FROM dag
airflow-scheduler_1  | WHERE dag.dag_id = %(dag_id_1)s
airflow-scheduler_1  |  LIMIT %(param_1)s]
airflow-scheduler_1  | [parameters: {'dag_id_1': 'match_annotated_titles', 'param_1': 1}]
airflow-scheduler_1  | (Background on this error at: http://sqlalche.me/e/f405)
```

**Comment by jdu** [comment]
Did you merge master into your neural branch or rebase it? I'm guessing your branch is significantly behind master so you'll need to probably rebase your branch and resolve any merge conflicts. then shut down docker-compose, delete the `build` folder, run 'make docker-build` and then `docker-compose up`. There's been enough significant change since you branched off master that I'm guessing whatever you have set up in local might be borked as the issue above is airflow trying to retrieve information about a DAG from the postgres database. We've also updated airflow so it might be that the old postgres structure doesn't work with the newer version of airflow.

**Comment by ivyleavedtoadflax** [comment]
Yep i merged master into the deep_reference_parser branch, and resolved the conflicts before doing anything. Actually the above traceback was from `master` itself, not my branch.

Interestingly, rebuilding the containers even whilst specifying `--no-cache` and `docker-compose down -v` did not resolve this, but deleting the `./build` folder and then rebuilding did.

**Comment by ivyleavedtoadflax** [comment]
I still get the following error, but it doesn't appear to be terminal:

```

airflow-scheduler_1  | [2020-02-04 13:12:20,101] {celery_executor.py:264} ERROR - Error fetching Celery task state, ignoring it:IntegrityError('(psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"\nDETAIL:  Key (typname, typnamespace)=(taskset_id_sequence, 2200) already exists.\n',)
airflow-scheduler_1  | Celery Task ID: ('policy-test', 'Spider.gov_uk', datetime.datetime(2020, 2, 4, 13, 12, 15, 923965, tzinfo=<TimezoneInfo [UTC, GMT, +00:00:00, STD]>), 1)
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
airflow-scheduler_1  |     cursor, statement, parameters, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
airflow-scheduler_1  |     cursor.execute(statement, parameters)
airflow-scheduler_1  | psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "pg_type_typname_nsp_index"
airflow-scheduler_1  | DETAIL:  Key (typname, typnamespace)=(taskset_id_sequence, 2200) already exists.
airflow-scheduler_1  |
airflow-scheduler_1  |
airflow-scheduler_1  | The above exception was the direct cause of the following exception:
airflow-scheduler_1  |
airflow-scheduler_1  | Traceback (most recent call last):
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/airflow/executors/celery_executor.py", line 106, in fetch_celery_task_state
airflow-scheduler_1  |     res = (celery_task[0], celery_task[1].state)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 475, in state
airflow-scheduler_1  |     return self._get_task_meta()['status']
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/result.py", line 414, in _get_task_meta
airflow-scheduler_1  |     return self._maybe_set_cache(self.backend.get_task_meta(self.id))
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/base.py", line 451, in get_task_meta
airflow-scheduler_1  |     meta = self._get_task_meta_for(task_id)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 51, in _inner
airflow-scheduler_1  |     return fun(*args, **kwargs)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 151, in _get_task_meta_for
airflow-scheduler_1  |     session = self.ResultSession()
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/database/__init__.py", line 110, in ResultSession
airflow-scheduler_1  |     **self.engine_options)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/database/session.py", line 59, in session_factory
airflow-scheduler_1  |     self.prepare_models(engine)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/celery/backends/database/session.py", line 54, in prepare_models
airflow-scheduler_1  |     ResultModelBase.metadata.create_all(engine)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/schema.py", line 4316, in create_all
airflow-scheduler_1  |     ddl.SchemaGenerator, self, checkfirst=checkfirst, tables=tables
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2049, in _run_visitor
airflow-scheduler_1  |     conn._run_visitor(visitorcallable, element, **kwargs)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1618, in _run_visitor
airflow-scheduler_1  |     visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
airflow-scheduler_1  |     return meth(obj, **kw)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 781, in visit_metadata
airflow-scheduler_1  |     _is_metadata_operation=True,
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
airflow-scheduler_1  |     return meth(obj, **kw)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 815, in visit_table
airflow-scheduler_1  |     self.traverse_single(column.default)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/visitors.py", line 138, in traverse_single
airflow-scheduler_1  |     return meth(obj, **kw)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 859, in visit_sequence
airflow-scheduler_1  |     self.connection.execute(CreateSequence(sequence))
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
airflow-scheduler_1  |     return meth(self, multiparams, params)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
airflow-scheduler_1  |     return connection._execute_ddl(self, multiparams, params)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1044, in _execute_ddl
airflow-scheduler_1  |     compiled,
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
airflow-scheduler_1  |     e, statement, parameters, cursor, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
airflow-scheduler_1  |     util.raise_from_cause(sqlalchemy_exception, exc_info)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
airflow-scheduler_1  |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
airflow-scheduler_1  |     raise value.with_traceback(tb)
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
airflow-scheduler_1  |     cursor, statement, parameters, context
airflow-scheduler_1  |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 588, in do_execute
airflow-scheduler_1  |     cursor.execute(statement, parameters)
airflow-scheduler_1  | sqlalchemy.exc.IntegrityError: (psycopg2.errors.UniqueViolation) duplicate key value violates unique constraint "pg_type_typname_nsp_index"
airflow-scheduler_1  | DETAIL:  Key (typname, typnamespace)=(taskset_id_sequence, 2200) already exists.
airflow-scheduler_1  |
airflow-scheduler_1  | [SQL: CREATE SEQUENCE taskset_id_sequence]
airflow-scheduler_1  | (Background on this error at: http://sqlalche.me/e/gkpj)
```

**Comment by jdu** [comment]
@ivyleavedtoadflax Dropping the volumes with the `-v` option only really drops the mounts, not the actual data within the mounts. Once the containers start back up they re-create the mounts to the same location on your file system so it just picks up the same data as before. The build folder is mounted into the container image as the place for airflow to write postgres and airflow data. So if you delete the build folder and then start it up it should start from scratch.

I'll have a go with a fresh build in a moment to see if I can reproduce this.

**Comment by jdu** [comment]
@ivyleavedtoadflax Looking at the secondary error you have above, a SEQUENCE in PG is when you declare a SERIAL, for instance an auto-incremented integer primary key which is expected to incremenet by one on each insert would result in the creation of a SEQUENCE to store the state of that serial. In this instance, it's saying one already exists, so there's potentially an issue there where there is still data in the database but i'm not sure how if you removed the build folder already. It's non-critical as whatever was intending to use that sequence will still operate but it might be that we need to make sure that the airflow components in docker-compose start in a specific order potentially.
